### ISSUE TITLE
typo in trackstats.py

### ISSUE THREAD

**Issue by HJarausch** [akkana/pytopo#4] opened 2019-05-14 10:26 UTC
Hi,
I need to apply the following modification
sed -i -e's/from MapUtils import/from pytopo.MapUtils import/' pytopo/trackstats.py

Furthermore, is there a mean to export the map window as png file or similar?
Many thanks,
Helmut

**Comment by akkana** [comment] 2019-05-14 15:07
I'm pretty sure you're right, but the way I have it set up for testing on my system, it works either way, so it hides the problem. I'm leading up to a new PyTopo release anyway, so I need to set up a better testing environment that will show problems like that. I'll do that as soon as I can (and check in the fix). Thanks for the report.

**Comment by akkana** [comment] 2019-05-14 19:01
I can't make it fail; every way I try it, it works whether or not I import from pytopo.MapUtils or plain MapUtils. I'm trying things like (after removing anything that has a link to my debugging environment):

```
virtualenv ~/.python2test
. ~/.python2test/bin/activate
cd ~/src/pytopo
python setup.py install
ellie path_to_track_file.gpx
```
and I don't see the error you're seeing. What command are you running when you see the errork what platform are you on, and what Python version?

I believe you about the error, and I'm pretty sure you're right that it should be changed, but I'm bothered that I can't reproduce it and so therefore I can't test whether the fix works, or whether it might happen again in the future.

**Comment by HJarausch** [comment] 2019-05-14 20:36
First, you use  from pytopo.MapUtils import MapUtils in all other files like
TiledMapCollection.py GenericMapCollection.py MapWindow.py TopoMapCollection.py 
but not in trackstats.py

I'm using Python-3.7.3 on my Gentoo system.
Invoking  /usr/bin/pytopo  I get an error 'no module MapUtils' unless I do the change mentioned
in my first comment.

**Comment by akkana** [comment] 2019-05-14 21:49
Interesting. I hadn't tried it in Python 3 because I haven't finished the Python 3 port yet, so I didn't think it would even get that far. And for me, it doesn't: for me it dies in the very first import in __init__.py,
from .MapCollection import MapCollection. I'm testing in a virtualenv using Python 3.7.3rc1 (that seems to be the version Debian Testing has right now) so there shouldn't be any major differences between that and your Gentoo 3.7.3. I wonder why you don't see the errors from __init__.py before you get to the trackstats.py problem.

Porting to Python3 has been an ongoing long-term project; first I had to get it working with GTK3 and GIO since PyGTK isn't available in Python3 and never will be. I think that part is done now, though, so probably it's time to work on that.

**Comment by akkana** [comment] 2019-05-15 00:08
I got the imports from __init__.py working in Python 3 here, and have checked in the changes.

I still can't reproduce the problem you're seeing from trackstats.py. I wish I could figure out what the difference is. You're right that it should be consistent with the other files, but I sure would like to track down why we're seeing such different things before closing the bug. I just tried installing the latest on a raspberry pi with the default user (so I know I don't have any PATH or PYTHONPATH customization) and running it in python 3.5.3 there, and I don't see it there either.

**Comment by HJarausch** [comment] 2019-05-15 14:26
When I undo the fix in pytopo/trackstats.py  I get
./pytopo --help
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.7/pytopo", line 11, in <module>
    load_entry_point('pytopo==1.6', 'gui_scripts', 'pytopo')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/pytopo/__init__.py", line 18, in <module>
    from .GenericMapCollection import GenericMapCollection
  File "/usr/lib/python3.7/site-packages/pytopo/GenericMapCollection.py", line 14, in <module>
    from pytopo.MapWindow import MapWindow
  File "/usr/lib/python3.7/site-packages/pytopo/MapWindow.py", line 18, in <module>
    from . import trackstats
  File "/usr/lib/python3.7/site-packages/pytopo/trackstats.py", line 18, in <module>
    from MapUtils import MapUtils
ModuleNotFoundError: No module named 'MapUtils'

**Comment by akkana** [comment] 2019-06-18 01:43
I've tried all sorts of setups on different machines, both python2 and python3, and I can't find any way to reproduce the problem. But I've added the "pytopo." anyway, since it makes sense to be consistent.

**Closed by akkana** 2019-06-18 01:43 UTC
